---
booktitle: Proceedings of the 1st Workshop on Healthcare AI and COVID-19, ICML 2022
shortname: WHAC
volume: '184'
year: '2022'
start: 2022-07-22
end: 2022-07-22
published: 2022-07-21
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: WHAC-2022
month: 0
cycles: false
bibtex_editor: Xu, Peng and Zhu, Tingting and Zhu, Pengkai and Clifton, David A. and
  Belgrave, Danielle and Zhang, Yuanting
editor:
- given: Peng
  family: Xu
- given: Tingting
  family: Zhu
- given: Pengkai
  family: Zhu
- given: David A.
  family: Clifton
- given: Danielle
  family: Belgrave
- given: Yuanting
  family: Zhang
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the 1st Workshop on Healthcare AI and COVID-19, ICML 2022
    Held in Baltimore, Maryland, USA on 22 July 2022

  Published as Volume 184 by the Proceedings of Machine Learning Research on 21 July 2022.

  Volume Edited by:
    Peng Xu
    Tingting Zhu
    Pengkai Zhu
    David A. Clifton
    Danielle Belgrave
    Yuanting Zhang

  Series Editors:
    Neil D. Lawrence
date_str: 22 Jul
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v184"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v184
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v184
email: ''
conference:
  name: Workshop on Healthcare AI and COVID-19
  url: https://healthcare-ai-covid19.github.io/
  location: Baltimore, Maryland, USA
  dates:
  - 2022-07-22
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v184/ICML2022-COVID-healthcare-workshop.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v184/ICML2022-COVID-healthcare-workshop.bib
